/*----- PROTECTED REGION ID(PowerPMAC_IOStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PowerPMAC_IOStateMachine.cpp
//
// description : State machine file for the PowerPMAC_IO class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PowerPMAC_IO.h>

/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::PowerPMAC_IOStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  


namespace PowerPMAC_IO_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PowerPMAC_IO::is_RawValue_allowed()
 *	Description : Execution allowed for RawValue attribute
 */
//--------------------------------------------------------
bool PowerPMAC_IO::is_RawValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PowerPMAC_IO::RawValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::RawValueStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PowerPMAC_IO::RawValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::RawValueStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMAC_IO::is_Value_allowed()
 *	Description : Execution allowed for Value attribute
 */
//--------------------------------------------------------
bool PowerPMAC_IO::is_Value_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PowerPMAC_IO::ValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::ValueStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PowerPMAC_IO::ValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::ValueStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PowerPMAC_IO::is_ScaleFactor_allowed()
 *	Description : Execution allowed for ScaleFactor attribute
 */
//--------------------------------------------------------
bool PowerPMAC_IO::is_ScaleFactor_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ScaleFactor attribute in Write access.
	/*----- PROTECTED REGION ID(PowerPMAC_IO::ScaleFactorStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::ScaleFactorStateAllowed_WRITE

	//	Not any excluded states for ScaleFactor attribute in read access.
	/*----- PROTECTED REGION ID(PowerPMAC_IO::ScaleFactorStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::ScaleFactorStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(PowerPMAC_IO::PowerPMAC_IOStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PowerPMAC_IO::PowerPMAC_IOStateAllowed.AdditionalMethods

}	//	End of namespace
