//=============================================================================
//
// file :        MultiClassessFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible for the creation of
//               all class singleton for a device server. It is called
//               at device server startup.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <tango.h>
#include <PowerPMAC_GlobalClass.h>
#include <PowerPMAC_IOClass.h>
#include <PowerPMAC_ProgramsClass.h>
#include <PowerPMAC_MotorClass.h>
#include <PowerPMAC_CoordinateSystemsClass.h>

/**
 *	Create Class singletons and store them in DServer object.
 */

void Tango::DServer::class_factory()
{
	add_class(PowerPMAC_Global_ns::PowerPMAC_GlobalClass::init("PowerPMAC_Global"));
	add_class(PowerPMAC_IO_ns::PowerPMAC_IOClass::init("PowerPMAC_IO"));
	add_class(PowerPMAC_Programs_ns::PowerPMAC_ProgramsClass::init("PowerPMAC_Programs"));
	add_class(PowerPMAC_Motor_ns::PowerPMAC_MotorClass::init("PowerPMAC_Motor"));
	add_class(PowerPMAC_CoordinateSystems_ns::PowerPMAC_CoordinateSystemsClass::init("PowerPMAC_CoordinateSystems"));
}
