/*----- PROTECTED REGION ID(PowerPMAC_CoordinateSystemsStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PowerPMAC_CoordinateSystemsStateMachine.cpp
//
// description : State machine file for the PowerPMAC_CoordinateSystems class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PowerPMAC_CoordinateSystems.h>

/*----- PROTECTED REGION END -----*/	//	PowerPMAC_CoordinateSystems::PowerPMAC_CoordinateSystemsStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace PowerPMAC_CoordinateSystems_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(PowerPMAC_CoordinateSystems::PowerPMAC_CoordinateSystemsStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PowerPMAC_CoordinateSystems::PowerPMAC_CoordinateSystemsStateAllowed.AdditionalMethods

}	//	End of namespace
