/*----- PROTECTED REGION ID(PowerPMAC_CompensationTableClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        PowerPMAC_CompensationTableClass.h
//
// description : Include for the PowerPMAC_CompensationTable root class.
//               This class is the singleton class for
//                the PowerPMAC_CompensationTable device class.
//               It contains all properties and methods which the 
//               PowerPMAC_CompensationTable requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef PowerPMAC_CompensationTableClass_H
#define PowerPMAC_CompensationTableClass_H

#include <tango.h>
#include <PowerPMAC_CompensationTable.h>


/*----- PROTECTED REGION END -----*/	//	PowerPMAC_CompensationTableClass.h


namespace PowerPMAC_CompensationTable_ns
{
/*----- PROTECTED REGION ID(PowerPMAC_CompensationTableClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	PowerPMAC_CompensationTableClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute SourceMotor class definition
class SourceMotorAttrib: public Tango::Attr
{
public:
	SourceMotorAttrib():Attr("SourceMotor",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~SourceMotorAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->read_SourceMotor(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->write_SourceMotor(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_SourceMotor_allowed(ty);}
};

//	Attribute TargetMotor class definition
class TargetMotorAttrib: public Tango::Attr
{
public:
	TargetMotorAttrib():Attr("TargetMotor",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~TargetMotorAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->read_TargetMotor(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->write_TargetMotor(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_TargetMotor_allowed(ty);}
};

//	Attribute From class definition
class FromAttrib: public Tango::Attr
{
public:
	FromAttrib():Attr("From",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~FromAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->read_From(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->write_From(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_From_allowed(ty);}
};

//	Attribute To class definition
class ToAttrib: public Tango::Attr
{
public:
	ToAttrib():Attr("To",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~ToAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->read_To(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->write_To(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_To_allowed(ty);}
};

//	Attribute CompensationTable class definition
class CompensationTableAttrib: public Tango::SpectrumAttr
{
public:
	CompensationTableAttrib():SpectrumAttr("CompensationTable",
			Tango::DEV_DOUBLE, Tango::READ_WRITE, 100) {};
	~CompensationTableAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->read_CompensationTable(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<PowerPMAC_CompensationTable *>(dev))->write_CompensationTable(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_CompensationTable_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command ResetTarget class definition
class ResetTargetClass : public Tango::Command
{
public:
	ResetTargetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetTargetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetTargetClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PowerPMAC_CompensationTable *>(dev))->is_ResetTarget_allowed(any);}
};


/**
 *	The PowerPMAC_CompensationTableClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  PowerPMAC_CompensationTableClass : public Tango::DeviceClass
#else
class PowerPMAC_CompensationTableClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(PowerPMAC_CompensationTableClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	PowerPMAC_CompensationTableClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static PowerPMAC_CompensationTableClass *init(const char *);
		static PowerPMAC_CompensationTableClass *instance();
		~PowerPMAC_CompensationTableClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		PowerPMAC_CompensationTableClass(string &);
		static PowerPMAC_CompensationTableClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	PowerPMAC_CompensationTable_H
